### ISSUE TITLE
import path issue.

### ISSUE THREAD

**Issue by imfox** [Perryvw/TypescriptToLua#129]
![img](https://raw.githubusercontent.com/imfox/imgStore/master/tstl.png)

I don't think it's right.

**Comment by lolleko** [comment]
Inport paths in lua are tricky we basically have to use the path from the project root. Looks like there is something wrong with selecting the root dir.... i will have a look

**Comment by lolleko** [comment]
Couple of things: I just realised you are importing a definition file (d.ts). That shouldn't actually get required. I will fix that.

For the issue regarding the path to be resolved wrong, thats because you use baseUrl we don't support that currently. But we could probably add support for that aswell.

**Comment by lolleko** [comment]
So actually importing declaration files is fine and allowed in typescript so we will allow it too. But tbh you probably shouldn't do that.

BaseUrl support will be added with #132 and will be in the next release.

**Comment by imfox** [comment]
Is there any better way to do it?

**Comment by Perryvw** [comment]
If you set up your project using a tsconfig it will automatically include any definition files it finds in your source paths and you won't have to include them explicitly.

**Comment by imfox** [comment]
thx :)
