### ISSUE TITLE
Question: Factorio CustomTables

### ISSUE THREAD

**Issue by badgamernl** [Perryvw/TypescriptToLua#227]
Hello, I'm trying to make a deceleration file for Factorio but how would you go about making this https://lua-api.factorio.com/latest/LuaCustomTable.html into a declaration file?

Currently have this but there must be a better way:
```ts
declare class player {
  name: string;
  index: number;
  print: (message: any) => void;
}

declare namespace game {
    const players: { [key: string]: player };
}
```

**Comment by Perryvw** [comment]
Looks like you are on the right track! I will give my thoughts on how to write declarations here, maybe we can put it on the wiki as example later!

I prefer looking at classes one by one, there is a strong correlation between API classses and declarations ones. The file you linked `LuaCustomTable` would be the first class to declare. I think it would be nice if we can declare the kind of things that go in the table (unless there are mixed classes in which case wtf factorio) so we use a generic type:
```
declare class LuaCustomTable<TElement> {
    [key: string]: TElement;
    valid: boolean;
    help(): string;
}
```
Now that we have a table, let's look at what to put in. In the example they mention the `LuaPlayer` class which can be defined 1:1 according to its documentation:
```
declare class LuaPlayer {
   set_ending_screen_data(message: string, file: string?): void;
    print(message:string, color: string): void;
    clear_console(): void;
    ....
```
Then you can indeed declare the game namespace like you did, but with our new types:
```
declare namespace game {
    players: CustomLuaTable<LuaPlayer>;
}
```

Disclaimer: I currently have no way to actually verify any of this works so I am just doing this from memory, you might actually need to declare interfaces instead of classes, it might be nice to add public/private modifiers and I might have missed some stuff.

**Comment by badgamernl** [comment]
thanks, currently working on parsing the Factorio API to automate it so this will help 👍

**Comment by Perryvw** [comment]
Had the chance to actually check what I wrote, I updated my other post. You will have to do some trial and error to check the translation is correct or not, I can also refer you to [our wiki](https://github.com/Perryvw/TypescriptToLua/wiki/Custom-Decorators) which contains info on extra decorators you might need it to make the translation behave correctly in Factory.

Let me know how this works out, this might be a good example/tutorial to put on our wiki!
