### ISSUE TITLE
Falsey values?

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#231]
There's a big discrepancy between lua and js regarding 'falsey' values. In lua, only 'nil' and 'false' are will evaluate as false, while in js there are a number of values that will, including the number zero (0) and empty strings ("").

It seems like this is something that should be handled when transpiling since this statement will currently evaluate as true in lua but false in js:
```ts
if (0) { /* do something */ }
```
But, this could introduce a lot of undesirable overhead, so I'm curious what thoughts are around this.

- Is it something that should be handled or should users be aware that the rules are different?
- If handled, should there be a compiler option to disable it, to improve performance?
- If not handled maybe a compiler warning when non-boolean expressions are used in conditions?

**Comment by lolleko** [comment]
I think we discussed this a long time ago and came to the conclusion that this is something the programmer has to handle himself.

The same way a programmer has to know that `NaN` evaluates to false in js and `77 == '77'` to true. He also has to know that `""`/`0` are true in Lua and `77 == '77'` is false. Aswell that 0 is false and !0 is true in C...
My point is I don't think this is an issue we have to solve, since inconsistent true/false behaviour is something you always have to think about while programming anyway.

Also it probably would not be practical to check every single expression for truthy/falsey values and transform them or emit a warning. It could also be impossible to check consistently.

Personally I think its great that we can get rid of javascripts weird falsey truthy behaviour, and the tripple equals madness. I've seen very little use cases for this behaviour (I never used double equals).

**Comment by tomblind** [comment]
Sounds pretty reasonable to me. The overhead of getting perfect compatibility probably isn't worth it and I agree in these cases lua's rules are much more sane. As @lolleko said, mentioning it in the docs would probably be a good idea, though.

**Comment by dmarcuse** [comment]
Maybe having a config option to switch between Lua and JS behavior?

**Comment by Perryvw** [comment]
Created a page for this on the wiki https://github.com/Perryvw/TypescriptToLua/wiki/Differences-between-Lua-and-Javascript
