### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#240]
* Semicolons on empty lines [Playground link](https://typescripttolua.github.io/#src=%20%20button.onclick%20%3D%20function()%20%7B%0A%20%20%20%20alert(greeter.greet())%3B%0A%20%20%7D%0A%0A%20%20)

* comment `--Lualib Library import` at the top of a file if `importkind == inline` even if no lualib features are used [Playground link](https://typescripttolua.github.io/#src=%20%20button.onclick%20%3D%20function()%20%7B%0A%20%20%20%20alert(greeter.greet())%3B%0A%20%20%7D%0A%0A%20%20)

* continue label and additional scope even if continue is not used [Playground link](https://typescripttolua.github.io/#src=for%20(const%20unit%20of%20enemies)%20%7B%0A%0A%7D%0A%0A%0A%20%20)

I am sure there are more of these small issues, but thats all I can think of right now.

**Comment by tomblind** [comment]
Not sure if this counts, but else-ifs are not pretty right now. Instead of using lua's 'elseif', they get nested (which is particularly bad with lua 5.1 where switch-case isn't supported).

[Playground link](https://typescripttolua.github.io/#src=declare%20let%20foo%3A%20number%3B%0Aif%20(foo%20%3D%3D%201)%20%7B%0A%7D%20else%20if%20(foo%20%3D%3D%202)%20%7B%0A%7D%20else%20if%20(foo%20%3D%3D%203)%20%7B%0A%7D%0A)

**Comment by lolleko** [comment]
I guess this can be close when the new Printer is shipped with 1.0.0

**Comment by lolleko** [comment]
Already fixed in branch `ts-to-lua-ast`
