### ISSUE TITLE
Consider separating AST transformation and printing phases

### ISSUE THREAD

**Issue by ark120202** [Perryvw/TypescriptToLua#265]
For my unmaintained project, [babel-lua](https://github.com/ark120202/babel-lua), I have implemented a [Lua AST printer](https://github.com/ark120202/babel-lua/tree/master/packages/lua-generator), which supports most of Lua's syntax (everything expect comments, but it looks like it's not supported there as well).

Using it allows to split transformation and printing phases, allowing them to develop separately. Using it also resolves #237, as it already has source map support, and adds a feature to minify printed result (though only on code style level, as it not includes AST transformation features like mangling or dead code elimination).

It also already has defined [types](https://github.com/ark120202/babel-lua/blob/master/packages/lua-generator/src/index.d.ts) and utilities for creating AST - [lua-types](https://github.com/ark120202/babel-lua/blob/master/packages/lua-types/src/index.d.ts).

**Comment by Perryvw** [comment]
I think doing something like this is unavoidable if we want to support source maps.

It might also be an interesting idea to split any adjustments done on the typescript AST before transforming to lua as a separate phase instead of in the process of parsing. Maybe in the future we could have 3 phases like 'transform TS AST' -> 'map to lua AST' -> output.

**Comment by lolleko** [comment]
tracked in #278
